const List<String> phrase = [
  "É em meio a dificuldade que se encontra a oportunidade",
  "O êxito é ir de frustração a frustração sem perder a animação",
  "Mesmo que algo pareça difícil, nunca desista antes de tentar",
  "Você é o único que entende as suas dificuldades, por isso motive se a prosseguir",
  "Não é uma vida ruim, é apenas um dia ruim, lembre-se disso",
  "A maior prova de que você pode fazer o impossível, é superar circunstâncias difíceis",
  "Que os dias bons se tornem rotina, e os ruins se tornem raros",
  "É genial celebrar a vitória, contudo é mais significativo aprender com as lições da derrota",
  "Qualquer dificuldade pode ser ultrapassada, já que para todo problema há uma solução",
  "Já pensou que você já superou muitas dificuldades até aqui?",
  "Suas pequenas vitórias são todas as dificuldades superadas durante sua vida, tenha orgulho delas",
  "Cada dificuldade ultrapassada te faz mais forte",
  "Desistir não deve ser considerado, mesmo que as coisas não sejam fáceis",
  "O êxito é a somatória dos pequenos esforços repetidos diariamente",
  "Para quem está iluminado, os dias de luz sempre retornam",
  "Conheci o pior das pessoas e o melhor de mim, passando por tempos difíceis",
  "Você não vai encontrar ninguém para sorrir por ti, então não deixe de sorrir",
  "Mesmo que nem todo dia seja bom, há algo de bom todo dia",
  "Em dias difíceis, lembre-se do que Deus já fez por ti, Recorde o que pode te oferecer esperança",
  "Da mesma forma que a felicidade não dura para sempre, a tristeza também não",
  "As dores não são eternas, se permita, o seu melhor é o suficiente",
  "Mesmo que a jornada seja lenta, abrir mão não acelera",
  "Que a expectativa por dias melhores nunca nos falte",
  "Você é maior do que toda essa tormenta, seja resiliente",
  "A vida é um eterno recomeço",
  "O fruto do que você escolher hoje, é o que você viverá amanhã",
  "Ser uma pessoa melhor é o objetivo do dia",
  "Se nada der certo hoje, acorde mais cedo amanhã e tente novamente",
  "Você nunca irá fazer nada, se ficar esperando pelas situações perfeitas",
  "O futuro ainda não chegou, seja grato pelo agora",
  "Para chegar em lugares maravilhosos, é necessário passar por caminhos difíceis",
  "As estrelas mais brilhantes são produzidas nas noites mais escuras",
  "A diferença entre os dias ruins e bons, é que um ensina e o outro marca",
  "A superação da dificuldade depende apenas de você ",
  "Se não está feliz com algo, mexa se!",
  "Mesmo que a conquista venha apenas às vezes, não deixe de lutar",
  "Está na hora de deixar o passado no lugar dele e seguir em frente",
  "Superação é esquecer o ontem para um amanhã melhor e promitente",
  "Domine os seus medos!",
  "Você não chegou até aqui por acaso, para tudo existe uma razão, Continue em frente",
  "Você terá possibilidade de ganhar, enquanto tiver força para lutar",
  "Seus medos morrerão de fome, se alimentar a sua motivação",
  "Vencer momentos difíceis pede esforço, entretanto todos somos capacitados para isso, recomeçar e escolher um novo caminho",
  "Problemas não são barreiras, mas chances de ímpares de superação e desenvolvimento",
  "Você só será vencedor se lutar hoje e sempre, que os fracassos da vida não sejam motivo para tristeza",
  "Diversas coisas me fizeram sofrer, entretanto elas somente precisavam acontecer para me fazer crescer",
  "Não importa se o obstáculo é forte, difícil ou grande demais, pois a persistência para vencer supera qualquer coisa",
  "Conforme você superar cada desafio, você sentirá que com motivação e fé nada é impossível de acontecer",
  "Não há outra forma de crescer, senão superar os desafios e os medos, Deixe-os vir",
  "Nenhum desafio vai ser impossível de superar, se tiver paciência e determinação, Tudo vai dar certo",
  "Está enganado quem pensa que o meu coração cheio de cicatrizes não tem forças para prosseguir",
  "O caminho para realizar nossos sonhos fica menor, a cada passo de superação que damos",
  "Em um mundo cheio de adversidades, quem não desiste sempre sairá como vencedor no final",
  "Até que ser forte seja a sua única opção, você não saberá o quão forte você é",
  "As pedras que atrapalham a sua jornada hoje, irão enfeitar a sua estrada amanhã, Siga em frente e não se dê por derrotado",
  "Existem momentos em que caímos, mas nos reerguemos melhor do que antes",
  "Permita-se começar e recomeçar quantas vezes forem necessárias",
  "Apenas grandes guerreiros recebem grandes batalhas",
  "As pequenas vitórias devem ser superadas",
  "Tentar é sinônimo de vencer",
  "Aprenda a ignorar as coisas para ser feliz",
  "Quando você aprender que tem que se levantar sozinho, você vai aprender a ser forte",
  "Você não está voltando para trás, então não olhe para lá",
  "A sua competição é com você mesmo",
  "Se não batalhar por nada, você será derrotado por qualquer coisa"
      "Você só vai vencer amanhã, se não desistir hoje",
  "Respire fundo e continue, é proibido desistir",
  "Não tenha medo de crescer devagar, tenha medo somente de ficar parado",
  "Se você não tiver animação para acreditar que pode mudar, as coisas vão permanecer iguais",
  "Aquilo que você não tenta, é a única coisa impossível",
  "Todos os seus amanhã permanecerão iguais a ontem, se você não modificar hoje",
  "Não desista agora, cada esforço vai valer a pena",
  "Faça o que a maioria não faz, se quiser chegar onde a maioria não chega",
  "É o empenho e a persistência que determinam o seu êxito, não a força ou a sorte",
  "A primeira pessoa que tem que acreditar nos seus sonhos é você mesmo, não aguarde pelo incentivo dos outros",
  "Acredite em você, nos seus sonhos e nas suas ideias",
  "Não foque em ser ocupado, foque em ser produtivo",
  "Você pode controlar qualquer coisa no futuro, se aprender a se controlar",
  "Coloque fé em seus sonhos, e não limites",
  "Acredite na sua capacidade e conquiste o seu lugar,",
  "Você se aproxima cada vez mais do seu objetivo, a cada passo que você dá",
  "Entre você e o seu propósito só há uma barreira: você",
  "É essencial para a nossa evolução reconhecer quem somos",
  "Você é digno de tudo o que almeja e merecedor de tudo o que possui",
  "A partir do momento em que você passa a focar em você, a única lamentação que você terá é a de não ter feito isso antes",
  "Cruzar lutas, dificuldades e dores faz parte da jornada, Entretanto, é você quem escolhe se vai deixá-los te vencerem ou se é você quem vai vencê-los",
  "A pessoa que você escolhe ser, é a única pessoa que você está fadado a se tornar",
  "Esteja em paz consigo, vivendo a sua verdade",
  "Não é necessário agradar as outras pessoas",
  "Confie no seu potencial, encare os seus medos e faça da bravura o seu mantra diário",
  "Lute pela sua felicidade escutando o que o seu coração diz",
  "É dentro de você que está a superação",
  "Dê pequenos passos diariamente",
  "O que a mente acredita é o que o corpo vai alcançar",
  "Não ache que vai acordar resistente todos os dias, o cansaço também faz parte",
  "Os seus resultados são determinados pelas suas atitudes",
  "A vida retribui quem pensa positivo",
  "Não utilize a régua de outro, para medir a sua evolução",
  "Não faça sempre o mesmo, se está procurando por resultados distintos",
  "Você é a única pessoa capaz que tem capacidade para mudar o seu trajeto, confie mais no seu potencial",
  "Verá que não existe o impossível se acreditar em você mesmo",
  "Eu chegarei onde eu quiser, custe o que custar, Pois eu acredito em cada um dos meus sonhos e acredito em mim",
  "Você sempre vai ser o inimigo mais perigoso que você poderá encontrar",
  "Dizer para si mesmo \"hoje eu vou vencer\", é a melhor forma para começar o dia",
  "O maior dedo do meio de todos os tempos, é o amor próprio",
  "Conquistamos muito aos poucos, sendo justamente quem somos",
  "Você tem a capacidade para dominar o mundo, com o seu esforço e sendo você mesmo",
  "Deixe de se preocupar com a pessoa que você vai ser futuramente e mantenha o foco em amar quem você é hoje",
  "Apenas você mesmo sabe a força que você possui",
  "Você se supera de alguma forma diariamente e isso já basta para você entender quanto é capaz",
  "É ideal que você se concentre em ser a melhor pessoa que puder ser, para assim conseguir alcançar o êxito com solidez",
  "O fruto vai vir na mesma intensidade do seu esforço",
  "Lute diariamente para que a sua capacidade se sobressaia no seu trabalho",
  "Existe apenas uma pessoa a qual você deve tentar ser melhor: a pessoa que você era ontem",
  "Mesmo que não seja evidente nenhum retorno, dê o seu melhor todos os dias",
  "Em meio a várias personalidades padrão, ser você mesmo é um ato de ousadia",
  "Para voltar a ser feliz, apenas o amor próprio é necessário",
  "Se esforce, se arrisque e permita se, exiba para você mesmo do que você é capaz",
  "Você pode, se acreditar que pode",
  "Não deixe que ninguém te menospreze, reconheça o seu valor, pois você é incrível",
  "Você é merecedor de uma vida feliz, não se autossabote",
  "Seja e faça o melhor que puder",
  "Você tem o superpoder para fazer hoje ser um ótimo dia",
  "Até que tenha orgulho de você, não pare",
  "Não sou perfeita, sou apenas melhor do que ontem",
  "O seu plano mais importante é você mesmo",
  "Quando você se acostuma a confiar em si mesmo, as coisas começam a dar certo",
  "Até a porta fechada se transforma em boa notícia, quando você está seguro da promessa de Deus para você!",
  "Fé e segurança, ter isso é motivador",
  "Sua força vem de Deus, então jamais duvide",
  "Muitas vezes, o que você pensa que é um abismo, é Deus te ensinando a progredir, amadurecer e a voar",
  "Eu não iria conseguir chegar até aqui sem Deus",
  "Continue caminhando, continue crendo, continue esperando",
  "Deus chama de processo, o que você diz ser atraso",
  "Deve aceitar o futuro que vier, quem não luta pelo futuro que deseja",
  "Continue acreditando em Deus, não importa quão difícil pareça ser",
  "Ou você tem fé na vida ou não tem, E se a fé existir dentro de você, que seja inabalável",
  "A salvação é encontrada na fé, Deus é maior do que a sua dificuldade",
  "Há algo maior do que qualquer aflição, basta apenas que você acredite",
  "Jamais abra mão do que você pede para Deus todos os dias",
  "Conseguimos crer no magnífico, fazer o impossível e enxergar o invisível, quando temos fé em Deus",
  "A falta de fé pode te fazer cair, jamais a perca",
  "A voz de Deus te encoraja a seguir, quando tudo está dizendo que não",
  "Em meio aos altos e baixos da vida, jamais abra mão da sua alma, do seu sorriso e da sua fé",
  "Mesmo que você não entenda o plano de Deus, confie nele, Isso é ter fé",
  "A sua fé é uma força que ninguém pode tirar de ti",
  "Resolva de joelhos o que você não consegue resolver em pé, pois Deus irá fazer por ti o que você não consegue",
  "Que a fé sempre vença a tristeza e o desânimo",
  "Fica em pé diante de qualquer coisa, aquele que fica de joelhos diante de Deus",
  "Deus não muda suas promessas",
  "Não deixe que a luta vença a sua fé",
  "Que a fé que habita dentro de nós, sempre vença o desânimo e a tristeza",
  "Mesmo que a minha solução não caia do céu, a minha força vem de lá",
  "Aquele que tem fé, não precisa ter sorte",
  "A fé não torna as coisas fáceis, torna-as possíveis",
  "As grandes mudanças da vida podem acontecer com o simples ato de acreditar",
  "A persistência da fé é a esperança",
  "Tudo dá certo quando colocamos a nossa fé em ação",
  "Na oração recarregamos a força, que a luta vem e nos tira",
  "Só enxergamos novos horizontes quando damos um passo à frente",
  "Não existe êxito dentro da zona de conforto",
  "Livre-se da zona de conforto se deseja ser feliz, É com mudança e movimento que se alcança a mudança",
  "Creia, transforme e arrisque",
  "Para se desenvolver é necessário renascer e se transformar",
  "Para sair da zona de conforto é necessário ter coragem e confrontar o medo do desconhecido",
  "Sem mudanças, não existe evolução e crescimento, lembre-se disso",
  "Não permita que a zona de conforto te defina, ela é estática e infértil",
  "Pegue as mudanças da vida como oportunidades de evolução e renovação",
  "É necessário abrir mão do comodismo de tempos em tempos, Sair em busca de novos ares e largar a zona de conforto",
  "O futuro pode ser muito melhor, brilhante e bonito, Para isso, apenas confie e tenha coragem para abandonar tudo o que limita o seu presente",
  "Conceitos novos não circulam em mentes quadradas",
  "Não rosne, se não tiver bravura para morder",
  "Você não é uma árvore, Por isso, se está infeliz com algo, mova-se",
  "Arrisque-se, Se der certo, fique feliz, Se não der certo, abrace como sabedoria",
  "Quando você começa a fazer modificações e para de dar desculpas, a maturidade vem",
  "É necessário que você aja para a mudança, apenas querer ser diferente não é o suficiente",
  "Quem não tem bravura para iniciar algo, faz o mais fácil: condenar",
  "Saber que mudança simboliza recomeço é a melhor maneira para ser feliz",
  "Modificar-se faz parte da jornada da vida",
  "A vida sempre vai te oferecer infinitas oportunidades para recomeçar",
  "Busque pela sua força e ganhe todos os desafios da vida",
  "Não abra mão sem tentar novamente",
  "Tentar é a única maneira de saber se vai dar certo",
  "Use os pensamentos positivos para se libertar da gaiola de angústias e medos,",
  "Você pode voar alto, acredite!",
  "Arrisque-se, A vida é ampla e cheia de novidades, Saia da sua zona de conforto",
  "Começar é o segredo do progresso",
  "A observação dos detalhes faz grandes ideias surgirem",
  "Ao mudarmos nós mesmos, mudamos o mundo",
  "É você quem escolhe se hoje será apenas mais um dia, ou se é o dia em que fará tudo mudar",
  "Se livre do medo de errar, errado é deixar a oportunidade ir embora",
  "Quando você bate as suas asas com amor, perseverança e foco, o voo é inevitável",
  "Nunca deixe que uma dificuldade atrapalhe você de chegar ao seu êxito, não se deixe levar pelo abatimento",
  "Se você continuar dormindo os seus sonhos não vão se realizar",
  "Em meio aos planos, desejos e sonhos, o importante é jamais desistir",
  "Faça tudo com determinação e mesmo que não tenha êxito você irá se sentir vitorioso",
  "Quando você não vença com dignidade, ganhar se torna um fracasso",
  "Quem perde de sorriso no rosto e cabeça levantada, é tão vencedor quanto quem ganha",
  "Quando obtém conhecimento, você nunca sai perdendo",
  "Só porque um sonho se mostrou ser mais difícil do que parecia, não desista dele",
  "Os sonhos acabam virando realidade, no passo a passo sem desistir",
  "Nunca desistir é a chave para o êxito profissional",
  "É a determinação para alcançar os meus sonhos, que me move",
  "A constância dos objetivos é o segredo do êxito",
  "Para alcançar o êxito, o esforço, a paciência e a persistência são um combo imbatível",
  "Para quem estuda não existe derrota, Ou aprende, ou ganha!",
  "Aprenda a ser disciplinado, pois nem sempre você estará motivado",
  "Se preocupe com a sua força de vontade para realizar os seus sonhos, e não com o tamanho deles",
  "Abra-se para a coragem e vá atrás dos seus sonhos",
  "Os sonhos aparecem realizados quando se tem a atitude certa",
  "Faça a vida acontecer direcionada para a manifestação dos seus sonhos e ao seu passo",
  "Não existe o acaso, tudo depende de você",
  "Se ainda existir desejo, é sinal que você está no caminho certo para o êxito, Não desista",
  "Use o seu sucesso para responder aqueles que duvidaram de você",
  "O ímã para o êxito é o pensamento positivo, O pensamento negativo atrai apenas a frustração",
  "Anseie, estruture e realize!",
  "Desejar ter êxito sem trabalhar, é a mesma coisa de aguardar a colheita sem ter plantado",
  "O empenho é o verdadeiro nome do sucesso",
  "Seja uma boa pessoa, antes de ser um bom profissional",
  "O reflexo do nosso empenho é o nosso êxito",
  "Não tenha medo de abrir mão do bom, para ir ao extraordinário",
  "Quando existe determinação, os sonhos se tornam visões do futuro",
  "Pode ter certeza que fazendo com determinação, amor e vontade, você sempre irá colher bons frutos",
  "O êxito de amanhã é a determinação de hoje",
  "É a partir da sua determinação que a mudança começa",
  "É a minha determinação que me faz ganhar",
  "A chave para você que quer conquistar algo, é a determinação",
  "A determinação é o maior triunfo do vencedor",
  "A melhor parte da conquista é a determinação de ganhar",
  "A sua determinação tem como consequência o êxito",
  "A crítica negativa se transforma em motivação quando você está determinado a agir",
  "É a falta de determinação e coragem que impedem a realização dos sonhos",
  "A sua determinação irá te levar onde você nem imagina",
  "Para chegar onde quiser basta apenas ser determinado",
  "Com determinação tudo pode ser alcançado, mesmo que a jornada seja difícil",
  "Melhor do que ter força de vontade, é ter atitude",
  "O impulso vital que tem a capacidade de te levar mais longe, é a força de vontade",
  "Aquele que tem determinação para resolver os problemas, não se assusta com eles",
  "Você já tem metade da batalha ganha, com determinação, Você é capaz, acredite!",
  "É necessário transformar a imaginação em determinação e empenho, para ter um sonho realizado",
  "A determinação fica em silêncio dormindo dentro de você, Mas quando os seus desejos começam a falar mais alto, ela acorda",
  "Se inspire em mais uma batalha que você vai ganhar, erguendo a sua cabeça e olhando para o céu",
  "Imagine como seria a vida dos seus sonhos e lute para que eles se tornem realidade",
  "A vitória é um fruto de muita determinação, E não um golpe de sorte",
  "É para onde o foco vai que a energia flui",
  "Não deixe as suas dores definirem o seu futuro, e sim a sua confiança",
  "Maior do que a sua determinação, deve estar a sua habilidade",
  "Não adianta ter vontade, se você não tiver determinação",
  "A imaginação cria, a vontade atrai e a fé faz acontecer, Siga firme em direção ao seu objetivo",
  "O que separa as outras pessoas das pessoas bem-sucedidas é a determinação",
  "Seu maior medo também pode ser sua maior motivação",
  "Inspiração vem dos outros, Motivação vem de dentro de nós",
  "Não é fácil, mas com a dose certa de motivação, a gente conquista!",
  "Faço da dificuldade a minha motivação – Charlie Brown Jr ",
  "Fracasso é a palavra de motivação para o sucesso – André Guerreiro ",
  "A alegria é a fonte de todo prazer, e a satisfação da motivação – Junior Do Vale",
  "A motivação é uma porta que se abre por dentro – Mario Sergio Cortella",
  "Sempre há um caminho melhor, então não perca a motivação e siga tentando",
  "Muitas vezes não é a motivação que precisa mudar, e sim, o foco – Raphael Michael ",
  "Consciente das dificuldades, procuro sempre encontrar motivação para os meus sonhos",
  "Alcançar o que tanto queremos, pode depender apenas de uma pequena dose de coragem",
  "O sucesso é a soma de pequenos esforços repetidos dia após dia – Robert Collier ",
  "Valorize as pequenas conquistas",
  "A segurança é principalmente uma superstição, A vida é uma aventura ousada ou nada – Helen Keller ",
  "Você não pode esperar por inspiração, Você tem que ir atrás dela",
  "A fotografia nunca se revela por inteiro quando você se desmancha por alguém, Essas relações lembram uma foto polaroid: a imagem vai aparecendo aos poucos, Algumas coisas se distanciam do sentimento original, mas isso é a vida - Mia Farrow",
  "Faça sempre o seu melhor mesmo que esse melhor não apareça na fotografia",
  "Quem tem luz própria nunca fica na escuridão, A fotografia irradia alegria e beleza ",
  "Minhas mãos te olham onde meus olhos te tocam - Lisa Carducci ",
  "Sem saber que era impossível, ele foi lá e fez!",
  "Quantas pessoas que estavam tristes consigo mesmo se contentaram em rasgar a própria fotografia! - Jules Reanrd ",
  "A melhor coisa sobre uma fotografia, é que ela não muda mesmo quando as pessoas mudam - Andy Warhol",
  "Só trabalhando é possível trilhar o caminho! ",
  "A inspiração existe, porém precisamos encontrá-la trabalhando",
  "A fotografia é uma das poucas coisas que tem poder sobre o tempo: ela o paralisa"
];
